### ISSUE TITLE
Recebendo "Remote Disconnection" na Imprensa Nacional

### ISSUE THREAD

**Issue by amilcar-EE** [Imprensa-Nacional/inlabs#2]
Olá!

Estamos seguindo o seu projeto para acessar a Imprensa-Nacional porém estamos recebendo um "remote disconnection". 

```
File "C:\Python37\lib\http\client.py", line 265, in _read_status
raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

Por favor, poderiam nos ajudar com este problema?

**Comment by Iakim** [comment]
Olá!

Parece ser um problema na biblioteca urllib3, vamos continuar investigando, mas em contra partida, pode-se usar o script no caminho https://github.com/Imprensa-Nacional/inlabs/tree/master/public/bash, que não utiliza a biblioteca urllib3, via bash.

**Comment by Iakim** [comment]
Prezado, a situação foi contornada com o script atualizado. Baixar a nova versão em https://github.com/Imprensa-Nacional/inlabs/tree/master/public/python.
