### ISSUE TITLE
Falhar ao estabelecer conexão

### ISSUE THREAD

**Issue by analise-ibpad** [Imprensa-Nacional/inlabs#4]
Estou tentando conectar no site do InLabs, mas não estou conseguindo estabelecer conexão. Existe alguma previsão de reestabelecer o site?

**Comment by evertonpalexandre** [comment]
Pessoal, estamos com problema ao conectar no InLabs... Existe alguma previsão? Abs

**Comment by Iakim** [comment]
Informo que estamos passando por uma instabilidade no site do INLabs, a equipe técnica está atuando para resolver o mais breve possível.

**Comment by Iakim** [comment]
Informo que o site já se encontra normalizado.
