### ISSUE TITLE
Falta e demora no upload dos arquivos XML zipados

### ISSUE THREAD

**Issue by analise-ibpad** [Imprensa-Nacional/inlabs#5]
Desde ontem estão aparecendo arquivos estranhos nas pastas diárias do InLabs, além da demora no upload dos arquivos zipados com os arquivos XML dos atos do Diário Oficial (além de arquivos incompletos). Hoje (07/12/2021), por exemplo, foi realizado apenas o upload de alguns poucos atos da seção 1 do DOU até agora 10h12. Apenas os arquivos PDF estão sendo subidos corretamente nas pastas.

**Comment by ArthurMenezes** [comment]
Adicionando uma possível inconsistência nesses arquivos zip com XMLs.
A edição de 06/12/2021 o arquivo final DO1.zip contém vários XMLs com 0bytes, isso é normal?

**Comment by analise-ibpad** [comment]
Sim, além disso existem diversos arquivos XML vazios.

**Comment by Iakim** [comment]
Informo que foi uma falha pontual, resolvido prontamente.
