### ISSUE TITLE
Link da matéria no site

### ISSUE THREAD

**Issue by joaocym** [Imprensa-Nacional/inlabs#6]
Bom dia,

Poderiam incluir no xml um campo com o link da matéria no site?

**Comment by Iakim** [comment]
Prezado João, tudo bem? Espero que sim!

Não há como incluir no XML o campo do link da matéria, pois o link da matéria é formado após a geração do XML.

Atenciosamente,
Isaac de Moraes

**Comment by Iakim** [comment]
Prezado João, tudo bem? Espero que sim!

Não há como incluir no XML o campo do link da matéria, pois o link da matéria é formado após a geração do XML.

Atenciosamente,
Isaac de Moraes
