### ISSUE TITLE
Disponibilidade de DOUs

### ISSUE THREAD

**Issue by HenriqueSydney** [Imprensa-Nacional/inlabs#9]
Alguma coisa aconteceu com os DOUs anterior à 22/02/2024? Fui tentar atualizar a base de uma aplicação que estou desenvolvendo, mas o último DOU disponível é o de 22/02/2024.

Ao acessar o https://inlabs.in.gov.br/index.php?p= diretamente também só constam os DOUs desde  22/02/2024. Tentando forçar a URL https://inlabs.in.gov.br/index.php?p=2024-02-21 também é redirecionado para a página  https://inlabs.in.gov.br/index.php?p=

**Comment by Iakim** [comment]
Boa tarde, tudo bem? a aplicação só guarda até 180 dias.
